<!DOCTYPE HMTL>
<html>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">What do you want for Dinner?</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="index.php">Eat everything!<span class="sr-only">(current)</span></a>
        </li>
      </ul>
      <span class="navbar-item">
        <a class="btn btn-danger navbar-btn" href="phrase_add.php">Neues Menü</a>

      </span>
    </div>
  </nav>

</html>